name: InfiniteClaims
main: sekonda.bukkit.InfiniteClaims.Main
author: Sekonda / Toffer
description: InfiniteClaims is a plugin designed for the InfinitePlots world generator to manage the plot allocation via WorldGuard. Originally coded by Toffer, rebuilt by Sekonda.
version: 2.0
commands:
  myplot:
    description: Returns you to your plot.
    aliases: [plothome]
    usage: Syntax error! Simply type /<command> to return to your plot.
  clearplot:
    description: This returns your plot back to the way it was originally.
    aliases: [emptyplot]
    usage: Syntax error! Simply type /<command> revert your plot back to the way it was originally. 
  getplot:
    description: This will give you a plot if you don't already have one.
    aliases: [newplot]
    usage: Syntax error! Simply type /<command> to get your very own plot.
depend: [InfinitePlots, WorldGuard]