main: hskrasek.InfiniteClaims
author: hskrasek
description: InfiniteClaims is a plugin designed for the InfinitePlots world generator to manage the plot allocation via WorldGuard. Originally coded by Toffer, rebuilt by Sekonda and hskrasek.
version: 1.7h
depend: [InfinitePlots, WorldGuard, WorldEdit]